### ISSUE TITLE
Fix Dockerfiles

### ISSUE THREAD

**Issue by markborkum** [markborkum/pacifica-proxymod#4]
### Pacifica REPLACE_ME version
n/a

### Pacifica Core Software versions
n/a

### Platform Details
n/a

### Scenario:
As the end-user, I want to start the "backend" and "frontend" Docker containers so that I can receive and handle event notifications.

### Steps to Reproduce:
The `docker-compose up backend` command starts RabbitMQ and Celery.

The `docker-compose up frontend` command starts uWSGI.

### Actual Result:

```
Step 13/13 : ENTRYPOINT [ "/bin/bash", "/usr/src/app/entrypoint-celery.sh" ]
 ---> Running in 5962109793da
Removing intermediate container 5962109793da
 ---> 49d82cdf331b

Successfully built 49d82cdf331b
Successfully tagged pacifica-proxymod_backend:latest
pacifica-proxymod_mysql_1 is up-to-date
pacifica-proxymod_rabbit_1 is up-to-date
Recreating pacifica-proxymod_backend_1 ... done
Attaching to pacifica-proxymod_backend_1
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/bin/celery", line 10, in <module>
backend_1   |     sys.exit(main())
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
backend_1   |     _main()
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
backend_1   |     cmd.execute_from_commandline(argv)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
backend_1   |     super(CeleryCommand, self).execute_from_commandline(argv)))
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
backend_1   |     argv = self.setup_app_from_commandline(argv)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
backend_1   |     self.app = self.find_app(app)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
backend_1   |     return find_app(app, symbol_by_name=self.symbol_by_name)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
backend_1   |     sym = symbol_by_name(app, imp=imp)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
backend_1   |     return imports.symbol_by_name(name, imp=imp)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
backend_1   |     module = imp(module_name, package=package, **kwargs)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
backend_1   |     return imp(module, package=package)
backend_1   |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
backend_1   |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend_1   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend_1   |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
backend_1   | ModuleNotFoundError: No module named 'pacifica.proxymod'
pacifica-proxymod_backend_1 exited with code 1
```

**Comment by markborkum** [comment]
Since a8ab798f2779c62c6efa197114814681ecfa93d1, the environment variable for the connection URL string for the database connection is `DATABASE_URL`.

Since 351c04774d7f318bf6d6c97fc7b90c46333473a6, the configuration file for URL connection strings (for downloaders and uploaders) and authentication is that of Pacifica CLI, e.g., `~/.pacifica_cli/config.ini`.
